amazonProperties:
  endpointUrl: https://s3.amazonaws.com
  accessKey: AKIAI5DBCHH2DLJSADGA
  secretKey: 5CF+3Ll7pS2B2SU7/I4Rb/34Mq5si9yB9WO+Euxj
  bucketName: microservice-image

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      database: example
      host: localhost
      port: 27017

server:
  port: 8084


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost