spring:
  application:
    name: eureka-service

server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  prefix: /api
  routes:
    db-user-service:
      path: /db-service/**
      url: http://localhost:8081