spring:
  application:
    name: login-signup-service
  data:
    mongodb:
      database: example
      host: localhost
      port: 27017

server:
  port: 8083


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost