rest:
  item:
    add: http://db-item-service/item/
    get: http://db-item-service/item/{id}
    update: http://db-item-service/item/
    delete: http://db-item-service/item/{id}
  items:
    get: http://db-item-service/item/{page}/{size}

amazonProperties:
  endpointUrl: https://s3.amazonaws.com
  accessKey: <ACCESS-KEY>
  secretKey: <SECRET-KEY>
  bucketName: <BUCKET-NAME>

spring:
  application:
    name: inventory-service

server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost

